# Generated by Django 6.0 on 2026-01-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('message', 'Nouveau message'), ('visit', 'Demande de visite'), ('visit_confirmed', 'Visite confirmée'), ('visit_refused', 'Visite refusée'), ('new_housing', 'Nouveau logement'), ('admin', 'Notification admin')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
