# Generated by Django 6.0 on 2026-01-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de visite')),
                ('time', models.TimeField(verbose_name='Heure de visite')),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('confirme', 'Confirmée'), ('refuse', 'Refusée'), ('annule', 'Annulée')], default='attente', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Message du locataire')),
                ('response_message', models.TextField(blank=True, verbose_name='Réponse du propriétaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='housing.housing')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-created_at'],
            },
        ),
    ]
