# Generated by Django 6.0 on 2026-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Message du locataire'),
        ),
        migrations.AddField(
            model_name='visit',
            name='message_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Message du locataire'),
        ),
        migrations.AddField(
            model_name='visit',
            name='response_message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse du propriétaire'),
        ),
        migrations.AddField(
            model_name='visit',
            name='response_message_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse du propriétaire'),
        ),
    ]
