# Generated by Django 6.0 on 2026-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_fr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
