# Generated by Django 6.0 on 2026-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
