# Generated by Django 6.0 on 2026-03-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_category_description_en_category_description_fr_and_more'),
        ('messaging', '0003_message_content_en_message_content_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='housing.housing'),
        ),
    ]
