# Generated by Django 6.0 on 2026-03-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_userpreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'Préférence utilisateur', 'verbose_name_plural': 'Préférences utilisateurs'},
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='nearby_places',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='priority',
            field=models.CharField(choices=[('price', 'Prix'), ('location', 'Emplacement'), ('comfort', 'Confort'), ('security', 'Sécurité')], default='price', max_length=20),
        ),
    ]
