# Generated by Django 6.0 on 2026-03-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alter_userpreference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='additional_features_en',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristiques supplémentaires'),
        ),
        migrations.AddField(
            model_name='housing',
            name='additional_features_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristiques supplémentaires'),
        ),
        migrations.AddField(
            model_name='housing',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='housing',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='housing',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='housing',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='housingtype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='housingtype',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='housingtype',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='housingtype',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_fr',
            field=models.TextField(null=True),
        ),
    ]
