# Generated by Django 6.0 on 2026-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('city', 'name')},
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name'), ('region', 'name_en'), ('region', 'name_fr')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('city', 'name'), ('city', 'name_en'), ('city', 'name_fr')},
        ),
    ]
