# Generated by Django 6.0 on 2026-01-27 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0002_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Chatbot',
                'verbose_name_plural': 'Conversations Chatbot',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('is_voice', models.BooleanField(default=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chatbot/audio/')),
                ('search_results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recherche.chatbotconversation')),
            ],
            options={
                'verbose_name': 'Message Chatbot',
                'verbose_name_plural': 'Messages Chatbot',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_weight', models.FloatField(default=0.3)),
                ('location_weight', models.FloatField(default=0.25)),
                ('size_weight', models.FloatField(default=0.2)),
                ('amenities_weight', models.FloatField(default=0.15)),
                ('proximity_weight', models.FloatField(default=0.1)),
                ('important_places', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_categories', models.ManyToManyField(blank=True, to='housing.category')),
                ('preferred_cities', models.ManyToManyField(blank=True, to='location.city')),
                ('preferred_districts', models.ManyToManyField(blank=True, to='location.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de recherche',
                'verbose_name_plural': 'Préférences de recherche',
            },
        ),
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place_type', models.CharField(choices=[('school', 'École'), ('supermarket', 'Supermarché'), ('hospital', 'Hôpital'), ('pharmacy', 'Pharmacie'), ('restaurant', 'Restaurant'), ('transport', 'Transport public'), ('bank', 'Banque'), ('market', 'Marché'), ('church', 'Église'), ('mosque', 'Mosquée'), ('park', 'Parc'), ('gym', 'Salle de sport'), ('other', 'Autre')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='location.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='location.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='location.region')),
            ],
            options={
                'verbose_name': 'Lieu à proximité',
                'verbose_name_plural': 'Lieux à proximité',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['place_type', 'city'], name='recherche_n_place_t_852d51_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(blank=True, max_length=500)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_rooms', models.IntegerField(blank=True, null=True)),
                ('max_rooms', models.IntegerField(blank=True, null=True)),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('advanced_filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('search_type', models.CharField(choices=[('form', 'Formulaire'), ('chatbot', 'Chatbot'), ('voice', 'Vocal')], default='form', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.district')),
                ('housing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.housingtype')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de recherche',
                'verbose_name_plural': 'Historiques de recherche',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recherche_s_user_id_afc0c1_idx'), models.Index(fields=['created_at'], name='recherche_s_created_0caa36_idx')],
            },
        ),
    ]
