# Generated by Django 6.0 on 2026-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmessage',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatbotmessage',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='address_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='query_text_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='query_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
